from rooms.projectroom1 import projectroom1

# state dictionary
state = {
    "current_room": "Lab2001",
    "rooms_visited": {
        "Lab2001": False,
        "EastCorridor": False,
        "Lab2003": False,
        "Lobby": False,
        "ProjectRoom1": False,
        "NorthCorridor": False,
        "FrontDeskOffice": False,
        "Classroom2015": False,
        "Classroom2021": False,
        "TeachersRoom1": False,
        "TeachersRoom2": False,
        "TeachersRoom3": False,
        "EquinoxStudentSociety": False,
        "ProjectRoom3": False,
        "Storage": False,
        "WestCorridor": False,
        "StairExit": False,
        "TeachersRoom4": False,
        "Classroom2031": False,
        "Classroom2035": False,
    },
    "inventory": {
        "Map": False,
        "Key1": False,
        "Key2": False,
        "Keycard": False,
        "Handle": False,
    },
}

# main loop
while True:
    match state["current_room"]:
        case "Lab2001": ...
        case "EastCorridor": ...
        case "Lab2003": ...
        case "Lobby": ...
        case "ProjectRoom1":
            projectroom1(state)
        case "NorthCorridor": ...
        case "FrontDeskOffice": ...
        case "Classroom2015": ...
        case "Classroom2021": ...
        case "TeachersRoom1": ...
        case "TeachersRoom2": ...
        case "TeachersRoom3": ...
        case "EquinoxStudentSociety": ...
        case "ProjectRoom3": ...
        case "Storage": ...
        case "WestCorridor": ...
        case "StairExit": ...
        case "TeachersRoom4": ...
        case "Classroom2031": ...
        case "Classroom2035": ...
